# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - redcarpet

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
domain:           visualcalculus.github.io 
url:              http://visualcalculus.github.io
baseurl:          /

author:
  name:           'Abhiroop Tejomay'

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/visualCalculus/visualcalculus.github.io
